{% set name = "pipe-rename" %}
{% set version = "1.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/marcusbuffett/pipe-rename/archive/{{ version }}.tar.gz
  sha256: 41edf419ab3d7b3c16d2efe209b3ca3d3f7104a3365f61fe821a59caac31810b

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - renamer --help

about:
  home: https://github.com/marcusbuffett/pipe-rename
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Rename your files using your favorite text editor
  dev_url: https://github.com/marcusbuffett/pipe-rename

extra:
  recipe-maintainers:
    - danielnachun
