context:
  version: "1.6.7"

package:
  name: pipe-rename
  version: ${{ version }}

source:
  url: https://github.com/marcusbuffett/pipe-rename/archive/${{ version }}.tar.gz
  sha256: 011d8ec263af85a9c2037098b1d5bf0ee271a3c1731e6de597bf02ccc81b55a2

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - renamer --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Rename your files using your favorite text editor
  homepage: https://github.com/marcusbuffett/pipe-rename
  repository: https://github.com/marcusbuffett/pipe-rename

extra:
  recipe-maintainers:
    - danielnachun
