context:
  version: "1.6.6"

package:
  name: pipe-rename
  version: ${{ version }}

source:
  url: https://github.com/marcusbuffett/pipe-rename/archive/${{ version }}.tar.gz
  sha256: bf33a2bba9b2d7ca4b13d35a0e49889ba77d8295314dd187f9709fe5ae6ac629

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - renamer --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Rename your files using your favorite text editor
  homepage: https://github.com/marcusbuffett/pipe-rename
  repository: https://github.com/marcusbuffett/pipe-rename

extra:
  recipe-maintainers:
    - danielnachun
